# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(885, 520)
        MainWindow.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        MainWindow.setDocumentMode(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tableItems = QtWidgets.QTableWidget(self.centralwidget)
        self.tableItems.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableItems.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableItems.setTabKeyNavigation(False)
        self.tableItems.setProperty("showDropIndicator", False)
        self.tableItems.setDragEnabled(False)
        self.tableItems.setDragDropOverwriteMode(False)
        self.tableItems.setDragDropMode(QtWidgets.QAbstractItemView.NoDragDrop)
        self.tableItems.setDefaultDropAction(QtCore.Qt.IgnoreAction)
        self.tableItems.setAlternatingRowColors(True)
        self.tableItems.setSelectionMode(QtWidgets.QAbstractItemView.ContiguousSelection)
        self.tableItems.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableItems.setTextElideMode(QtCore.Qt.ElideNone)
        self.tableItems.setShowGrid(False)
        self.tableItems.setGridStyle(QtCore.Qt.SolidLine)
        self.tableItems.setWordWrap(True)
        self.tableItems.setCornerButtonEnabled(True)
        self.tableItems.setRowCount(0)
        self.tableItems.setObjectName("tableItems")
        self.tableItems.setColumnCount(8)
        item = QtWidgets.QTableWidgetItem()
        self.tableItems.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableItems.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableItems.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableItems.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableItems.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableItems.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableItems.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableItems.setHorizontalHeaderItem(7, item)
        self.tableItems.horizontalHeader().setCascadingSectionResizes(True)
        self.tableItems.horizontalHeader().setDefaultSectionSize(150)
        self.tableItems.horizontalHeader().setHighlightSections(False)
        self.tableItems.horizontalHeader().setMinimumSectionSize(100)
        self.tableItems.horizontalHeader().setSortIndicatorShown(True)
        self.tableItems.horizontalHeader().setStretchLastSection(True)
        self.tableItems.verticalHeader().setVisible(False)
        self.tableItems.verticalHeader().setHighlightSections(False)
        self.verticalLayout_2.addWidget(self.tableItems)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnMovUp = QtWidgets.QPushButton(self.centralwidget)
        self.btnMovUp.setObjectName("btnMovUp")
        self.horizontalLayout.addWidget(self.btnMovUp)
        self.btnMovDwn = QtWidgets.QPushButton(self.centralwidget)
        self.btnMovDwn.setCheckable(False)
        self.btnMovDwn.setObjectName("btnMovDwn")
        self.horizontalLayout.addWidget(self.btnMovDwn)
        self.btnShuffle = QtWidgets.QPushButton(self.centralwidget)
        self.btnShuffle.setObjectName("btnShuffle")
        self.horizontalLayout.addWidget(self.btnShuffle)
        self.horizontalLayout_4.addLayout(self.horizontalLayout)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btnSelectAll = QtWidgets.QPushButton(self.centralwidget)
        self.btnSelectAll.setObjectName("btnSelectAll")
        self.horizontalLayout_2.addWidget(self.btnSelectAll)
        self.btnDeselect = QtWidgets.QPushButton(self.centralwidget)
        self.btnDeselect.setObjectName("btnDeselect")
        self.horizontalLayout_2.addWidget(self.btnDeselect)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.lineTitle = QtWidgets.QLineEdit(self.centralwidget)
        self.lineTitle.setMaxLength(30)
        self.lineTitle.setClearButtonEnabled(False)
        self.lineTitle.setObjectName("lineTitle")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineTitle)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.lineArtist = QtWidgets.QLineEdit(self.centralwidget)
        self.lineArtist.setMaxLength(30)
        self.lineArtist.setClearButtonEnabled(False)
        self.lineArtist.setObjectName("lineArtist")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineArtist)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.lineAlbum = QtWidgets.QLineEdit(self.centralwidget)
        self.lineAlbum.setMaxLength(30)
        self.lineAlbum.setClearButtonEnabled(False)
        self.lineAlbum.setObjectName("lineAlbum")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineAlbum)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.lineComment = QtWidgets.QLineEdit(self.centralwidget)
        self.lineComment.setMaxLength(28)
        self.lineComment.setFrame(True)
        self.lineComment.setClearButtonEnabled(False)
        self.lineComment.setObjectName("lineComment")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineComment)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.checkSetDate = QtWidgets.QCheckBox(self.centralwidget)
        self.checkSetDate.setText("")
        self.checkSetDate.setChecked(True)
        self.checkSetDate.setObjectName("checkSetDate")
        self.horizontalLayout_6.addWidget(self.checkSetDate)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_6.addWidget(self.label_5)
        self.formLayout.setLayout(4, QtWidgets.QFormLayout.LabelRole, self.horizontalLayout_6)
        self.dateYear = QtWidgets.QDateEdit(self.centralwidget)
        self.dateYear.setObjectName("dateYear")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.dateYear)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.checkSetTrack = QtWidgets.QCheckBox(self.centralwidget)
        self.checkSetTrack.setText("")
        self.checkSetTrack.setChecked(True)
        self.checkSetTrack.setObjectName("checkSetTrack")
        self.horizontalLayout_5.addWidget(self.checkSetTrack)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_5.addWidget(self.label_6)
        self.formLayout.setLayout(5, QtWidgets.QFormLayout.LabelRole, self.horizontalLayout_5)
        self.spinTrack = QtWidgets.QSpinBox(self.centralwidget)
        self.spinTrack.setObjectName("spinTrack")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.spinTrack)
        self.horizontalLayout_7.addLayout(self.formLayout)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.checkPreserve = QtWidgets.QCheckBox(self.centralwidget)
        self.checkPreserve.setChecked(True)
        self.checkPreserve.setObjectName("checkPreserve")
        self.verticalLayout.addWidget(self.checkPreserve)
        self.checkWriteEmpty = QtWidgets.QCheckBox(self.centralwidget)
        self.checkWriteEmpty.setObjectName("checkWriteEmpty")
        self.verticalLayout.addWidget(self.checkWriteEmpty)
        self.checkNumtoTrack = QtWidgets.QCheckBox(self.centralwidget)
        self.checkNumtoTrack.setChecked(False)
        self.checkNumtoTrack.setObjectName("checkNumtoTrack")
        self.verticalLayout.addWidget(self.checkNumtoTrack)
        self.checkUseFilename = QtWidgets.QCheckBox(self.centralwidget)
        self.checkUseFilename.setObjectName("checkUseFilename")
        self.verticalLayout.addWidget(self.checkUseFilename)
        self.lineFilenameRegex = QtWidgets.QLineEdit(self.centralwidget)
        self.lineFilenameRegex.setText("")
        self.lineFilenameRegex.setPlaceholderText("<:title:> - <:artist:> (<:year:>)")
        self.lineFilenameRegex.setObjectName("lineFilenameRegex")
        self.verticalLayout.addWidget(self.lineFilenameRegex)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem2 = QtWidgets.QSpacerItem(60, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.btnApply = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnApply.sizePolicy().hasHeightForWidth())
        self.btnApply.setSizePolicy(sizePolicy)
        self.btnApply.setMinimumSize(QtCore.QSize(0, 0))
        self.btnApply.setBaseSize(QtCore.QSize(0, 0))
        self.btnApply.setObjectName("btnApply")
        self.horizontalLayout_3.addWidget(self.btnApply)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_7.addLayout(self.verticalLayout)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 885, 22))
        self.menubar.setObjectName("menubar")
        self.menuFiles = QtWidgets.QMenu(self.menubar)
        self.menuFiles.setObjectName("menuFiles")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionFiles = QtWidgets.QAction(MainWindow)
        self.actionFiles.setObjectName("actionFiles")
        self.actionFolder = QtWidgets.QAction(MainWindow)
        self.actionFolder.setObjectName("actionFolder")
        self.menuFiles.addAction(self.actionFiles)
        self.menuFiles.addAction(self.actionFolder)
        self.menubar.addAction(self.menuFiles.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Mp3dit"))
        self.tableItems.setSortingEnabled(True)
        item = self.tableItems.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "#"))
        item = self.tableItems.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "File Name"))
        item = self.tableItems.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Title"))
        item = self.tableItems.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Artist"))
        item = self.tableItems.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Album"))
        item = self.tableItems.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Track"))
        item = self.tableItems.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Year"))
        item = self.tableItems.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Comment"))
        self.btnMovUp.setText(_translate("MainWindow", "Move Up"))
        self.btnMovDwn.setText(_translate("MainWindow", "Move Down"))
        self.btnShuffle.setText(_translate("MainWindow", "Shuffle"))
        self.btnSelectAll.setText(_translate("MainWindow", "Select All"))
        self.btnDeselect.setText(_translate("MainWindow", "Deselect All"))
        self.label.setText(_translate("MainWindow", "Title"))
        self.label_2.setText(_translate("MainWindow", "Artist"))
        self.label_3.setText(_translate("MainWindow", "Album"))
        self.label_4.setText(_translate("MainWindow", "Comment"))
        self.label_5.setText(_translate("MainWindow", "Year"))
        self.dateYear.setDisplayFormat(_translate("MainWindow", "yyyy"))
        self.label_6.setText(_translate("MainWindow", "Track"))
        self.checkPreserve.setText(_translate("MainWindow", "Preserve non empty fields"))
        self.checkWriteEmpty.setText(_translate("MainWindow", "Write empty strings in tags"))
        self.checkNumtoTrack.setText(_translate("MainWindow", "Set track number to item position"))
        self.checkUseFilename.setText(_translate("MainWindow", "Use file name to fill up fields"))
        self.btnApply.setText(_translate("MainWindow", "Apply"))
        self.menuFiles.setTitle(_translate("MainWindow", "Files..."))
        self.actionFiles.setText(_translate("MainWindow", "Open files..."))
        self.actionFolder.setText(_translate("MainWindow", "Open folder..."))
